### ISSUE TITLE
Updating a card

### ISSUE THREAD

**Issue by rcdeoliveira** [tghw/trello-py#15]
I'm trying to update a card, setting closed to True to hide it from the list:

`trello.cards.update(card["id"], closed=True)`

And this is the error I get:
```
Traceback (most recent call last):
  File "/home/rcdeoliveira/.local/bin/./update-trello.py", line 39, in <module>
    trello.cards.update(card["id"], closed=True)
  File "/home/rcdeoliveira/.local/lib/python3.10/site-packages/trello/cards.py", line 81, in update
    return self.raise_or_json(resp)
  File "/home/rcdeoliveira/.local/lib/python3.10/site-packages/trello/base.py", line 3, in raise_or_json
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trello.com/1/cards/{cardId}?key={key}&token={token}
```
Am I doing something wrong?

**Comment by rcdeoliveira** [comment]
To self answer my question

> I'm trying to update a card, setting closed to True to hide it from the list:
> 
> `trello.cards.update(card["id"], closed=True)`
> 
> And this is the error I get:
> 
> ```
> Traceback (most recent call last):
>   File "/home/rcdeoliveira/.local/bin/./update-trello.py", line 39, in <module>
>     trello.cards.update(card["id"], closed=True)
>   File "/home/rcdeoliveira/.local/lib/python3.10/site-packages/trello/cards.py", line 81, in update
>     return self.raise_or_json(resp)
>   File "/home/rcdeoliveira/.local/lib/python3.10/site-packages/trello/base.py", line 3, in raise_or_json
>     resp.raise_for_status()
>   File "/usr/lib/python3/dist-packages/requests/models.py", line 960, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://trello.com/1/cards/{cardId}?key={key}&token={token}
> ```
> 
> Am I doing something wrong?

To self answer my question, the issue was related with `closed=True`, the API expects the string `true` instead, so the right way to do it is with `closed="true"`
